project:
  type: website
  output-dir: "docs"
  render:
    - "*.qmd"
  resources:
    - "css"

website:
  title: "danielmiranda.com"
  description: "Daniel Miranda"
  image: images/Daniel_Miranda_Fuenzalida.jpg
  site-url: https://www.danielmiranda.com
  favicon: images/favicon/favicon.ico
  repo-url: https://github.com/kevin-carrasco/daniel-miranda
  search:
    location: navbar
    type: overlay
  back-to-top-navigation: false
  google-analytics: "G-HQNG5WQE3X"
  open-graph:
    locale: es_ES
    site-name: https://danielmiranda.com

  navbar:
    background: "#163754"
    right:
      - text: "Investigación"
        menu:
          - text: "Publicaciones"
            href: references/publications/index.qmd
          - text: "Capítulos de libro"
            href: references/chapters/index.qmd
          - text: "Presentaciones"
            href: references/presentations/index.qmd
      - text: "Docencia"
        href: docencia.qmd
      - text: "Proyectos"
        href: proyectos.qmd
  page-footer:
    center:
      - text: "<a href='https://www.danielmiranda.com/cv.html'>CV</a> &nbsp;<a href='https://github.com/damiranda' target='blank'><i class='bi bi-github'></i></a> &nbsp;<a href='https://www.linkedin.com/in/daniel-miranda-a0677921/' target='blank'><i class='bi bi-linkedin'></i></a> &nbsp;<a href='https://scholar.google.com/citations?user=vdF2kZcAAAAJ' target='blank'><i class='ai ai-google-scholar fa-lg'></i></a> &nbsp;<a href='https://www.researchgate.net/profile/Daniel-Miranda-13' target='blank'><i class='ai ai-researchgate fa-lg'></i></a> &nbsp;<a href='https://orcid.org/0000-0002-3143-8502' target='blank'><i class='ai ai-orcid fa-lg'></i></a><br>Site made with <a href='https://github.com/damiranda' target='_blank'><i class='bi bi-git'></i></a>, and <a href='https://quarto.org/' target='_blank'><img src='https://quarto.org/favicon.png' width=12> quarto</a><br>© 2026 Daniel Miranda"

format:
  html:
    theme: default
    css: css/theme.scss
    anchor-sections: true
    smooth-scroll: true
    link-external-newwindow: true
    link-external-icon: false
    lightbox: true
    # This is to include fontawesome and academic icons in the headers:
    include-in-header: "_includes/header.html"
